language: node_js
node_js:
  - "node"
# needs Ubuntu Trusty
dist: trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
  chrome: stable # have Travis install chrome stable.
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
